### your site title here
title: Sayem Mohammad Imtiaz
description: Postdoctoral Fellow at Tulane University

baseurl: "" #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: sayem@iastate.edu

highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

issues_repo: sayemimtiaz/site-comments

# Social media links in footer
# facebook: "#"
# twitter: "#"
linkedin: "sayemimtiaz"
github: "sayemimtiaz"
# researchgate: "#"
orcid: "0000-0002-0357-0098"
#google_analytics: ""
#scopus: "57195963279"
google_scholar: "217wW-YAAAAJ"
#flickr: "lorenzocarnevale"


# highlighter: rouge
# markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
# collections:
#   projects:
#     output: true
#     permalink: :path/projects/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - _bibliography

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
